import Link from "next/link";
import { ArrowRight, CalendarBlank, CheckCircle, GraduationCap, UsersThree } from "@phosphor-icons/react/dist/ssr";
import { FaqList } from "@/components/FaqList";
import { FeatureBand, FeatureItem } from "@/components/FeatureBand";
import { ImagePlaceholder } from "@/components/ImagePlaceholder";
import { PageHero } from "@/components/PageHero";
import { SectionHeading } from "@/components/SectionHeading";
import { filterAudience, getStudioContent } from "@/lib/content";

export const metadata = { title: "Für Schulen" };

export default async function SchoolsPage() {
  const content = await getStudioContent();
  const faq = filterAudience(content.faq, "schule");
  return <>
    <PageHero eyebrow="Für Schulen" title="Berufsorientierung, die ankommt." intro="Wir bringen Wirtschaft ins Klassenzimmer. Ohne großen organisatorischen Aufwand, mit klarer Vorbereitung und echten Gesprächen." imageLabel="Schülerinnen und Schüler im persönlichen Austausch" cta="Als Schule anfragen" ctaHref="/kontakt?rolle=schule" />
    <FeatureBand><FeatureItem icon={<GraduationCap size={30} weight="duotone" />} title="Direkt im Schulalltag" text="Das Format passt in Projekttage und Berufsorientierung." /><FeatureItem icon={<CalendarBlank size={30} weight="duotone" />} title="Planbar" text="Termin, Räume und Gesprächszeiten werden gemeinsam abgestimmt." /><FeatureItem icon={<UsersThree size={30} weight="duotone" />} title="Für Ihre Klassen" text="Jugendliche kommen unkompliziert mit Betrieben ins Gespräch." /><FeatureItem icon={<CheckCircle size={30} weight="duotone" />} title="Gut begleitet" text="Sie erhalten einen klaren Ablauf und eine feste Ansprechperson." /></FeatureBand>
    <section className="page-shell grid gap-10 py-20 sm:py-28 lg:grid-cols-[1.05fr_0.95fr] lg:items-center"><div className="prose-copy text-lg text-brand-ink/75"><p className="eyebrow">Was Sie erwartet</p><h2 className="display mt-3 text-4xl font-extrabold text-brand-navy sm:text-5xl">Ein Tag, der Orientierung persönlich macht.</h2><p className="mt-5">Wir helfen bei der Vorbereitung, koordinieren die teilnehmenden Unternehmen und schaffen einen sicheren Rahmen für die Gespräche.</p><ul><li>Praxisnahe Berufsorientierung ohne Bewerbungsdruck</li><li>Verschiedene Ausbildungsberufe an einem Ort</li><li>Einfacher Ablauf für Lehrkräfte und Klassen</li><li>Regionale Unternehmen persönlich kennenlernen</li></ul><Link href="/kontakt?rolle=schule" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-[10px] bg-brand-green px-6 font-bold text-white transition hover:bg-brand-navy">Termin besprechen <ArrowRight size={20} /></Link></div><ImagePlaceholder label="Ein Format, das in den Schulalltag passt" className="min-h-[24rem]" /></section>
    <section className="bg-white py-20 sm:py-28"><div className="page-shell grid gap-10 lg:grid-cols-[0.7fr_1.3fr] lg:items-start"><SectionHeading eyebrow="Für Lehrkräfte" title="Sie kennen Ihre Schule. Wir kennen den Ablauf." intro={<p>Gemeinsam klären wir Zielgruppe, Zeitfenster, Räume und die passende Auswahl an Unternehmen.</p>} /><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-[16px] bg-brand-mist p-6"><p className="display text-3xl font-bold text-brand-navy">01</p><h3 className="mt-4 font-display text-2xl font-bold text-brand-navy">Abstimmen</h3><p className="mt-2 text-brand-ink/75">Wir besprechen Anlass und Rahmenbedingungen.</p></div><div className="rounded-[16px] bg-brand-mist p-6"><p className="display text-3xl font-bold text-brand-navy">02</p><h3 className="mt-4 font-display text-2xl font-bold text-brand-navy">Vorbereiten</h3><p className="mt-2 text-brand-ink/75">Ihre Klassen wissen, was sie erwartet.</p></div><div className="rounded-[16px] bg-brand-mist p-6"><p className="display text-3xl font-bold text-brand-navy">03</p><h3 className="mt-4 font-display text-2xl font-bold text-brand-navy">Begegnen</h3><p className="mt-2 text-brand-ink/75">Unternehmen kommen direkt in die Schule.</p></div><div className="rounded-[16px] bg-brand-mist p-6"><p className="display text-3xl font-bold text-brand-navy">04</p><h3 className="mt-4 font-display text-2xl font-bold text-brand-navy">Weitergehen</h3><p className="mt-2 text-brand-ink/75">Nächste Kontakte und Schritte werden konkret.</p></div></div></div></section>
    {faq.length ? <section className="page-shell py-20 sm:py-28"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><SectionHeading eyebrow="FAQ für Schulen" title="Kurz beantwortet." /><FaqList items={faq} /></div></section> : null}
  </>;
}
